# Generated by Django 2.2.16 on 2022-12-17 12:38

from django.db import migrations, models
import users.validators


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_auto_20221217_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(max_length=200, validators=[users.validators.name_validator], verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=200, unique=True, validators=[users.validators.name_validator], verbose_name='Тег'),
        ),
    ]
